language: node_js
node_js: node

cache:
  npm: true
  directories:
  - $HOME/.pnpm-store/

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_APIKEY
  on:
    branch: master

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

install:
- pnpm i

script:
- pnpm run test

after_success:
- pnpm run coverage
