language: node_js
node_js: node

cache:
  npm: true
  directories:
  - $HOME/.pnpm-store/

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

install:
- pnpm i

script:
- pnpm run test

after_success:
- pnpm run coverage
- pnpm run build:storybook

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_APIKEY
    on:
      branch: master
  - provider: pages
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    local-dir: ./storybook-static
    on:
      branch: master
